cmd = ["hello.o", "syscalls.o", "-pie", "-zrelro"]
kind = "run-pass"
archs = ["x86", "x86_64"]
debug-print = ["layout", "final-elf=@segments"]

[[c]]
source = "hello.c"
libc = "freestanding"
relocation = "pic-only-got"

[[arch.x86.asm]]
source = "syscalls.32bit.S"
output = "syscalls.o"

[[arch.x86_64.asm]]
source = "syscalls.64bit.S"
output = "syscalls.o"
