[package]
name = "plink_elf"
version = "0.1.0"
edition = "2021"

[dependencies]
plink_utils = { path = "../plink_utils" }
plink_macros = { path = "../plink_macros" }

[dev-dependencies]
anyhow.workspace = true
insta.workspace = true
tempfile.workspace = true

[lints]
workspace = true
