archs = ["x86", "x86_64"]

[read-elf.read]
file = "${ld.hello}"
filter = "*hash,.dynsym"

[ld.hello]
output = "hello.so"
content = ["${c.hello}"]
shared-library = true

[c.hello]
source = "hello.c"
libc = "freestanding"
relocation = "pic"
