[package]
name = "plinky_test_harness"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
insta.workspace = true
plinky_macros.workspace = true
serde.workspace = true
tempfile.workspace = true
toml.workspace = true

[lints]
workspace = true
