[package]
name = "plinky_macros"
version = "0.1.0"
edition = "2021"

[dependencies]
plinky_macros_quote.workspace = true
plinky_utils.workspace = true

[lib]
proc-macro = true

[lints]
workspace = true
