[package]
name = "plinky_macros"
version = "0.1.0"
edition = "2021"

[dependencies]
plinky_macros_quote = { path = "../plinky_macros_quote/" }
plinky_utils = { path = "../plinky_utils/" }

[lib]
proc-macro = true

[lints]
workspace = true
