archs = ["x86_64"]

[plinky.missing_dir]
cmd = ["${asm.hello}"]
kind = "link-fail"
link-env = { PKG_CONFIG_PATH = "/dev/null" }

[plinky.parse_error]
cmd = ["${asm.hello}"]
kind = "link-fail"
link-env = { PKG_CONFIG_PATH = "${dir.pkg_config}" }

[dir.pkg_config]
files = ["libmean.pc"]

[asm.hello]
source = "hello.S"
