archs = ["x86_64"]

[plinky.test]
cmd = ["${asm.entry}", "--as-needed", "${ld.used}", "${ld.unused}", "${ld.dependency}"]
kind = "link-pass"
debug-print = ["loaded-object=@inputs"]

[ld.used]
output = "libused.so"
content = ["${asm.used}"]
shared-library = true

[ld.unused]
output = "libunused.so"
content = ["${asm.unused}"]
shared-library = true

[ld.dependency]
output = "libdependency.so"
content = ["${asm.dependency}"]
shared-library = true

[asm.entry]
source = "entry.S"

[asm.used]
source = "used.S"

[asm.unused]
source = "unused.S"

[asm.dependency]
source = "dependency.S"
