archs = ["x86", "x86_64"]

[read-elf.read]
file = "${ld.dynamic}"
filter = ".dyn*,*plt,@segments"

[read-dynamic.dynamic]
file = "${ld.dynamic}"

[ld.dynamic]
output = "dynamic.so"
content = ["${c.dynamic}"]
shared-library = true

[c.dynamic]
source = "dynamic.c"
libc = "freestanding"
relocation = "pic"
