cmd = ["hello.o", "syscalls.o", "-pie"]
kind = "link-pass"
archs = ["x86", "x86_64"]
debug-print = ["loaded-object=.text", "relocated-object=.text,.got,@symbols,@dynamic", "final-elf=.dyn*,.rel*,.*hash"]

[[c]]
source = "hello.c"
libc = "freestanding"
relocation = "pic-only-got"

[[arch.x86.asm]]
source = "syscalls.32bit.S"
output = "syscalls.o"

[[arch.x86_64.asm]]
source = "syscalls.64bit.S"
output = "syscalls.o"
