archs = ["x86", "x86_64"]

[plinky.no-pie-entry-no-pic]
cmd = ["${asm.entry_no_pic}", "${ld.data}", "${ld.syscalls}"]
kind = "link-fail"

[plinky.no-pie-entry-pic]
cmd = ["${asm.entry_pic}", "./${ld.data}", "./${ld.syscalls}"]
kind = "run-pass"
debug-print = [
    "loaded-object=@symbols,@inputs,.text,.text.main",
    "relocations-analysis",
    "final-elf=.dynamic,.dynsym,.rel*",
]

[plinky.pie]
cmd = ["-pie", "${asm.entry_pic}", "./${ld.data}", "./${ld.syscalls}"]
kind = "run-pass"
debug-print = [
    "loaded-object=@symbols,@inputs,.text,.text.main",
    "relocations-analysis",
    "final-elf=.dynamic,.dynsym,.rel*,.gnu.hash",
]

[asm.entry_pic]
source = "entry-pic.${arch}.S"

[asm.entry_no_pic]
source = "entry-no-pic.${arch}.asm"
assembler = "nasm"

[ld.data]
output = "libdata.so"
content = ["${asm.data}"]
shared-library = true

[asm.data]
source = "data.S"

[ld.syscalls]
output = "libsyscalls.so"
content = ["${asm.syscall_write}", "${asm.syscall_exit}"]
shared-library = true

[asm.syscall_exit]
source = "../_shared/syscall.exit.${arch}.S"

[asm.syscall_write]
source = "../_shared/syscall.write.${arch}.S"
