archs = ["x86", "x86_64"]

# TODO: test -no-pie (with a no-pic entry point)
# TODO: test -no-pie (with a pic entry point)

[plinky.pie]
cmd = ["-pie", "${asm.entry_pic}", "${ld.data}", "${ld.syscalls}"]
kind = "run-pass"
run-env = { LD_LIBRARY_PATH = "." }
debug-print = [
    "loaded-object=@symbols,@inputs,.text",
    "final-elf=.dynamic,.dynstr,.dynsym",
]

[asm.entry_pic]
source = "entry-pic.${arch}.S"

[ld.data]
output = "libdata.so"
content = ["${asm.data}"]
shared-library = true

[asm.data]
source = "data.S"

[ld.syscalls]
output = "libsyscalls.so"
content = ["${asm.syscall_write}", "${asm.syscall_exit}"]
shared-library = true

[asm.syscall_exit]
source = "../_shared/syscall.exit.${arch}.S"

[asm.syscall_write]
source = "../_shared/syscall.write.${arch}.S"
