[package]
name = "plinky_elf"
version = "0.1.0"
edition = "2021"

[dependencies]
plinky_utils.workspace = true
plinky_macros.workspace = true

[dev-dependencies]
anyhow.workspace = true
insta.workspace = true
tempfile.workspace = true

[lints]
workspace = true
