cmd = ["foo.o", "bar.o"]
kind = "run-pass"
debug-print = [
    "relocated-object=.custom_messages,.text",
    "layout",
    "final-elf=.custom-messages,.text,.strtab,.symtab",
]

[[asm]]
source = "foo.S"

[[asm]]
source = "bar.S"
