archs = ["x86_64"]

[plinky.test]
cmd = ["${asm.foo}", "${asm.bar}"]
kind = "run-pass"
debug-print = [
    "relocated-object=.custom_messages,.text",
    "layout",
    "final-elf=.custom-messages,.text,.strtab,.symtab",
]

[asm.foo]
source = "foo.S"

[asm.bar]
source = "bar.S"
