archs = ["x86", "x86_64"]

[plinky.static]
cmd = ["${c.hello_static}", "${asm.syscalls}"]
kind = "run-pass"

[plinky.static_got]
cmd = ["${c.hello_got}", "${asm.syscalls}"]
kind = "run-pass"
debug-print = ["loaded-object=.text", "relocated-object=.text,.got,@symbols"]

[plinky.pie_got]
cmd = ["${c.hello_got}", "${asm.syscalls}", "-pie"]
kind = "run-pass"
debug-print = [
    "loaded-object=.text",
    "layout",
    "relocated-object=.text,.got*,.interp,@symbols,@dynamic",
    "final-elf=.interp,.dyn*,.rel*,.*hash,@segments,@meta",
]

[plinky.pie_got_relro]
cmd = ["${c.hello_got}", "${asm.syscalls}", "-pie", "-zrelro"]
kind = "run-pass"
debug-print = ["layout", "final-elf=@segments"]

[plinky.pie_plt]
cmd = ["${c.hello_plt}", "${asm.syscalls}", "-pie"]
kind = "run-pass"
debug-print = [
    "loaded-object=.text",
    "layout",
    "relocated-object=.text,.got*,.plt,.interp,@symbols,@dynamic",
    "final-elf=.interp,.dyn*,.rel*,.*hash,@segments,@meta",
]

[plinky.pie_plt_now]
cmd = ["${c.hello_plt}", "${asm.syscalls}", "-pie", "-znow"]
kind = "run-pass"
debug-print = ["layout", "final-elf=.dynamic,@segments"]

[c.hello_static]
source = "hello.c"
libc = "freestanding"
relocation = "static"

[c.hello_got]
source = "hello.c"
libc = "freestanding"
relocation = "pic-only-got"

[c.hello_plt]
source = "hello.c"
libc = "freestanding"
relocation = "pic"

[asm.syscalls]
output = "syscalls.o"
source = "syscalls.${arch}.S"
